# .github/workflows/reusable-workflow.yaml
name: Reusable Workflow
on: workflow_call

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Reusable workflow executed"
