name: java CI with maven
on: push
branches: main
pull_request :
  branches: main

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: set up jdk 21
          uses: actions/setup-java@v4
          with:
            java-version: '11'
            distrubution: 'adopt'
            cache: maven

        - name: build with maven
          run: mvn -B package --file pom.xml

        - name: archive artifact
          uses: actions/upload-artifacts@v2
          with: 
          name: maven-web-application
          path: /home/runner/work/maven-web-application/maven-web-application/target/maven-web-application.war
          deploy:
            runs-on: ubuntu-latest
            needs: build
            steps:
              - name: Download Artifact
                uses: actions/download-artifacts@v2
                with:
                  name: maven-web-application
                  path: /opt

              - name: List Artifacts
                run: ls /opt
